[project]
name = "executor-dao"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/Users/fernandofoy/.clarinet/cache"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.executor-dao]
path = "contracts/executor-dao.clar"
depends_on = ["proposal-trait", "extension-trait"]

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
depends_on = []

[contracts.governance-token-trait]
path = "contracts/traits/governance-token-trait.clar"
depends_on = []

[contracts.nft-escrow]
path = "contracts/external/nft-escrow.clar"
depends_on = ["ownable-trait"]

[contracts.ownable-trait]
path = "contracts/traits/ownable-trait.clar"
depends_on = []

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
depends_on = []

[contracts.sip-010-trait]
path = "contracts/traits/sip-010-trait.clar"
depends_on = []

[contracts.zge000-governance-token]
path = "contracts/extensions/zge000-governance-token.clar"
depends_on = ["executor-dao", "governance-token-trait", "sip-010-trait"]

[contracts.zge001-proposal-voting]
path = "contracts/extensions/zge001-proposal-voting.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "governance-token-trait", "zge000-governance-token"]

[contracts.zge002-emergency-proposals]
path = "contracts/extensions/zge002-emergency-proposals.clar"
depends_on = ["executor-dao", "extension-trait", "zge001-proposal-voting"]

[contracts.zge003-emergency-execute]
path = "contracts/extensions/zge003-emergency-execute.clar"
depends_on = ["executor-dao", "extension-trait", "zge001-proposal-voting"]

[contracts.zge004-onboard-borrower]
path = "contracts/extensions/zge004-onboard-borrower.clar"
depends_on = ["executor-dao", "extension-trait"]

[contracts.zgp000-bootstrap]
path = "contracts/proposals/zgp000-bootstrap.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "zge000-governance-token", "zge001-proposal-voting", "zge002-emergency-proposals", "zge003-emergency-execute"]

[contracts.zgp001-kill-emergency-execute]
path = "contracts/proposals/zgp001-kill-emergency-execute.clar"
depends_on = ["zge003-emergency-execute", "executor-dao"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
